spring:
  application:
    name: eureka-client
server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9102/eureka/
      
cowboy:
  hello-server: eureka-client